/**
 * Shared types for the agent-transcript readers.
 *
 * These describe the query-time, read-only view assembled from an agent's own
 * session logs (Claude Code JSONL / Cursor SQLite). Nothing here is persisted
 * by unerr — it is reconstructed on demand for the dashboard prompt-trace view
 * (docs/logbook-page-redesign.md §10). The hot path never imports this module.
 */

/** Per-turn token totals summed from the agent's own usage accounting. */
export interface TokenUsage {
  /** New (uncached) input tokens billed for the turn. */
  input: number;
  /** Output tokens generated by the turn. */
  output: number;
  /** Tokens written into the prompt cache this turn (`cache_creation_*`). */
  cache_create: number;
  /** Tokens served from the prompt cache this turn (`cache_read_*`). */
  cache_read: number;
}

/**
 * One reconstructed conversation turn with its actual cost and execution
 * trace. `native_session_id` is the agent's own session id (Claude UUID /
 * Cursor conversationId), NOT unerr's 6-char hex — correlation between the two
 * is the consumer's (L7) job.
 */
export interface TurnTranscript {
  /** The agent's native session id (Claude `sessionId` UUID / Cursor convId). */
  native_session_id: string;
  /** Zero-based ordinal of this turn within the reconstructed chain. */
  turn_index: number;
  /** ISO-8601 start timestamp, or null when the source omits it. */
  started_ts: string | null;
  /** ISO-8601 end timestamp, or null when the source omits it. */
  ended_ts: string | null;
  /** Actual tokens used this turn (the net-new value over unfade-cli). */
  tokens_used: TokenUsage;
  /** Distinct tool names invoked this turn (e.g. ["Edit", "Bash"]). */
  tools: string[];
  /** Distinct filesystem paths the turn's tool calls touched. */
  files: string[];
  /** Model id for the turn, when the source records it. */
  model: string | null;
  /** Speaker role for the turn. */
  role: "user" | "assistant" | "system";
  /** Concatenated visible text for the turn (prompt for user, reply text for
   *  assistant). Tool-call payloads and thinking blocks are excluded. */
  text: string;
}

/** Which transcript reader an agent supports, or `null` when disabled. */
export type TranscriptCapability = "jsonl" | "sqlite" | null;
